name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install uv
        run: pip install uv
      - name: Sync repo
        run: uv sync
      - name: Run mypy
        run: uv run mypy src
